[package]
name = "rurekal"
version = "0.1.0"
authors = ["MeztliRA <MeztliRA@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
repl-rs = "0.2.4"